insert into user (Role, Username, password) VALUES ('MANAGER', 'aklein', 'password')
insert into user (Role, Username, password) VALUES ('MANAGER', 'pschmidt', 'password')
insert into user (Role, Username, password) VALUES ('MANAGER', 'bgross', 'password')
insert into user (Role, Username, password) VALUES ('MANAGER', 'mmueller', 'password')
insert into manager ( name , vorname , fachbereich, id_user ) values ( 'Klein', 'Anton ','Enterprise Java Development', 1)
insert into manager ( name , vorname , fachbereich, id_user) values ( 'Schmidt', 'Peter','APEX Development', 2)
insert into manager ( name , vorname , fachbereich, id_user) values ( 'Gross', 'Bernd','Microsoft Development', 3)
insert into manager ( name , vorname , fachbereich, id_user) values ( 'Mueller', 'Max','Oracle Java Development', 4)

insert into employee (id_manager) VALUES (1)
insert into employee (id_manager) VALUES (1)
insert into employee (id_manager) VALUES (1)
insert into employee (id_manager) VALUES (1)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (2)
insert into employee (id_manager) VALUES (3)
insert into employee (id_manager) VALUES (3)
insert into employee (id_manager) VALUES (3)
insert into employee (id_manager) VALUES (3)
insert into employee (id_manager) VALUES (3)
insert into employee (id_manager) VALUES (4)
insert into employee (id_manager) VALUES (4)
insert into employee (id_manager) VALUES (4)
insert into employee (id_manager) VALUES (4)
insert into user (role, username) VALUES ('EMPLOYEE', 1), ('EMPLOYEE', 2), ('EMPLOYEE', 3), ('EMPLOYEE', 4), ('EMPLOYEE', 5), ('EMPLOYEE', 6), ('EMPLOYEE', 7), ('EMPLOYEE', 8), ('EMPLOYEE', 9), ('EMPLOYEE', 12), ('EMPLOYEE', 15), ('EMPLOYEE', 17), ('EMPLOYEE', 19), ('EMPLOYEE', 20)

insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 1)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 4, 2017, 1)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 1)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 3, 2017, 1)
insert into vote (calendarweek, mood, year, id_employee) VALUES (34, 3, 2017, 1)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 3, 2017, 2)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 5, 2017, 2)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 2)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 4, 2017, 2)
insert into vote (calendarweek, mood, year, id_employee) VALUES (34, 5, 2017, 2)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 2, 2017, 3)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 3, 2017, 3)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 3, 2017, 3)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 5, 2017, 3)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 4)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 5, 2017, 4)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 1, 2017, 4)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 1, 2017, 5)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 3, 2017, 6)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 4, 2017, 6)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 6)
insert into vote (calendarweek, mood, year, id_employee) VALUES (33, 4, 2017, 6)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 3, 2017, 7)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 2, 2017, 7)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 7)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 8)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 3, 2017, 8)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 8)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 2, 2017, 8)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 2, 2017, 9)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 2, 2017, 9)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 4, 2017, 9)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 4, 2017, 12)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 3, 2017, 12)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 3, 2017, 12)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 4, 2017, 12)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 4, 2017, 15)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 2, 2017, 15)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 5, 2017, 15)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 5, 2017, 15)
insert into vote (calendarweek, mood, year, id_employee) VALUES (34, 5, 2017, 17)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 4, 2017, 17)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 17)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 3, 2017, 17)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 17)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 19)
insert into vote (calendarweek, mood, year, id_employee) VALUES (37, 3, 2017, 19)
insert into vote (calendarweek, mood, year, id_employee) VALUES (36, 4, 2017, 19)
insert into vote (calendarweek, mood, year, id_employee) VALUES (35, 4, 2017, 19)
insert into vote (calendarweek, mood, year, id_employee) VALUES (34, 5, 2017, 19)
insert into vote (calendarweek, mood, year, id_employee) VALUES (38, 5, 2017, 20)


